version: '2'

services:
  web:
    build: .
    volumes:
      - .:/app/client/public
    ports:
      - '4000:4000'
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
